### PR TITLE
Add Windows ARM64 CI

### PR DESCRIPTION
**Pull request by tommyvct**
As @nemequ asked in #860, I implemented Windows ARM64 CI on GitHub Action.

The CI itself is working fine, and it's doing its work of revealing problems between the toolchain and the project.

### CODE REVIEW

**Comment by nemequ** [comment]
Thanks, this is great!  For now I tweaked this a bit so it only nruns on the "msvc-arm" branch; it's going to take some time to fix all the issues, and I don't want the repo failing while we work on it.  At least now we have a path forward for proper MSVC on Arm support, though.

**Comment by tommyvct** [comment]
Just another thing came to my mind. There is another MSVC ARM configuration called `ARM64EC`. It's mostly the same thing compared to `ARM64` configuration, it also compiles to native ARM64 code and it even allows linking x64 DLLs and libraries to it. 

However, on pre-processor definition side, it's more alike to x64. It doesn't define `_M_ARM64` but `_M_ARM64EC` and `_M_X64`. 

Here's some reference: https://github.com/0xbadfca11/chpe_example

**Comment by nemequ** [comment]
Just FYI, all of the x86 headers should compile successfully on Arm with MSVC now (as of 6ecc0e3cdf4bbdab1a80fe76f9bd7b5887cf1f84)

**Comment by tommyvct** [comment]
Just FYI, it seems that the MSVC ARM64 CI isn't enabled, and I merged the `master` version onto my [Windows ARM64 fork of OBS Studio](https://github.com/tommyvct/obs-studio), and it failed to compile both on the CI and on my computer:
https://github.com/tommyvct/obs-studio/runs/3247407187   
image

**Comment by nemequ** [comment]
Yes, I did say "all of the x86 headers".  There are still problems with the NEON headers which I haven't had a chance to look at yet, as well as a bunch of warnings to clean up.  The errors from simde-math.h (e.g., "D:\a\obs-studio\obs-studio\libobs\util\simde\simde-math.h(1088,19): error C2039: 'round': is not a member of 'std' (compiling source file D:\a\obs-studio\obs-studio\plugins\win-wasapi\win-wasapi.cpp) [D:\a\obs-studio\obs-studio\build64\plugins\win-wasapi\win-wasapi.vcxproj]") are a bit disconcerting, though.

I'm still working on getting everything ported without warnings, it's just going to take some time.

**Comment by tommyvct** [comment]
> The errors from simde-math.h (e.g., "D:\a\obs-studio\obs-studio\libobs\util\simde\simde-math.h(1088,19): error C2039: 'round': is not a member of 'std' (compiling source file D:\a\obs-studio\obs-studio\plugins\win-wasapi\win-wasapi.cpp) [D:\a\obs-studio\obs-studio\build64\plugins\win-wasapi\win-wasapi.vcxproj]") are a bit disconcerting,

I can't wrap my head around it, since I'm using C17 and C++17, and `round()` should be in `cmath` and under `std` namespace. Do you have any idea on how could that be?

**Pull request closed without merging**
