### PR TITLE
arch: Add LoongArch LASX/LSX support

### PR DESCRIPTION
**Pull request by XiWeiGu**

### CODE REVIEW

**Comment by mr-c** [comment]
Thank you @XiWeiGu ; can you suggest how we can test LoongArch using Continuous Integration?

**Comment by XiWeiGu** [comment]
> Thank you @XiWeiGu ; can you suggest how we can test LoongArch using Continuous Integration?

Thank you for your reply. As far as I know there is no qemu or cross-toolchain support not at the time.  I only tested on the native LoongArch machine.

**Review by mr-c — APPROVED** [review]
Okay, I'll take this. I hope that a CI solution is added soon, so there aren't regression.

**Comment by XiWeiGu** [comment]
Thank you for your reply.  Continuous Integration can be achieved with the development of LoongArch ecology. I will submit the patch to increase CI in the next few days.

**Comment by mr-c** [comment]
This was merged as d0cc0abacbc4addd210d94ecdd5fa303e0b0e8ca & 31367e2b3263701987e3718a4179994bfd828eee !

**Comment by jiegec** [comment]
> Okay, I'll take this. I hope that a CI solution is added soon, so there aren't regression.

QEMU support for LSX/LASX has already been landed and released, we will just wait for the release of GCC 14, after which we can easily test them on CI.

**Pull request closed without merging**
