### PR TITLE
CI fixes

### PR DESCRIPTION
**Pull request by mr-c**
Hello, I'm one of the co-maintainers of SIMDe. [Evan](https://github.com/nemequ/) is busy with life things lately, and I'm more cheerleader than core dev for this project. Therefore anyone reading this is very welcome to send in suggestions for fixes!

### CODE REVIEW

**Comment by wrv** [comment]
For the power9 Travis CI build, is there a reason only half the number of processors is used? https://github.com/simd-everywhere/simde/blob/dd0b662fd8cf4b1617dbbb4d08aa053e512b08e4/.travis.yml#L17

**Comment by mr-c** [comment]
> For the power9 Travis CI build, is there a reason only half the number of processors is used? https://github.com/simd-everywhere/simde/blob/dd0b662fd8cf4b1617dbbb4d08aa053e512b08e4/.travis.yml#L17 

Good question. Let's try removing that!

**Comment by mr-c** [comment]
@wrv any thoughts on the emscripten failures? https://github.com/simd-everywhere/simde/actions/runs/3844466474/jobs/6547597103

**Comment by wrv** [comment]
I created another pull request for this branch to address the emscripten failure: https://github.com/simd-everywhere/simde/pull/976 

Since wasm-simd isn't an experimental feature anymore in v8, removing `--experimental-wasm-simd` was able to get the test passing.

The avx512 test seems to depend on the machine the Action is run on, and I'm not sure how to choose a particular CPU feature with Github Actions.

**Comment by wrv** [comment]
Github Actions will sometimes re-run the avx512 on different CPUs, so I split them into their own job and added a fail fast check by grepping the CPU features. The tests that fail because of this reason can be re-run on the CI page: 
image

Maybe there's a way to automatically re-run these tests?

**Comment by mr-c** [comment]
> Github Actions will sometimes re-run the avx512 on different CPUs, so I split them into their own job and added a fail fast check by grepping the CPU features. The tests that fail because of this reason can be re-run on the CI page: image
> 
> Maybe there's a way to automatically re-run these tests?

Yeah, this is why we were using Intel's Software Development Emulator to emulate AXV512 instructions as needed; but now it isn't working :-(

https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html

https://github.com/simd-everywhere/simde/blob/dd0b662fd8cf4b1617dbbb4d08aa053e512b08e4/test/check-flags.sh

**Comment by wrv** [comment]
For the icc job, there was a typo in `-Wno-tautological-constant-compare` (capital W required) and that Action now runs, but there are some failing tests. 

Results: https://github.com/wrv/simde/actions/runs/3884596322/jobs/6627371701

I tried `-fp-speculation=safe` locally as per [this StackOverflow post](https://stackoverflow.com/a/73534555/8169613) but that made more tests fail. 

The failing wasm_simd128 comparison tests seem to be due to a lack of NaN propagation with `SIMDE_MATH_NANF` but I'm not currently sure how to address it.

**Comment by mr-c** [comment]
@wrv we are making progress, thank you!

**Comment by wrv** [comment]
@mr-c what are the remaining issues to address in order to potentially get a new release?

**Comment by mr-c** [comment]
> @mr-c what are the remaining issues to address in order to potentially get a new release?

We need to decide what to do about the remaining failures (ignore + make an issue; or fix)

Then I'll clean up the commit history in this PR and merge

Then we can start on your other PR and then the release checklist: <https://github.com/simd-everywhere/simde/wiki/Release-Checklist>

**Comment by mr-c** [comment]
Fixed in https://github.com/simd-everywhere/simde/commit/08493a7184c5fa73f2d8ffdbe2051432ac519e41

**Pull request closed without merging**
