### PR TITLE
Add simde_mm512_srlv_epi{32,64}

### PR DESCRIPTION
**Pull request by anrodrig**
Mostly a copy of simde_mm512_srlv_epi16

### CODE REVIEW

**Comment by nemequ** [comment]
Thanks! ☺

I merged it into my working branch and wrote a test for it, it should hit master soon.

**Comment by AniesAliasGethub1** [comment]
Hi I'm here waiting your help to me

**Comment by nemequ** [comment]
> Hi I'm here waiting your help to me

Do you have a question?

If it's not related to this issue (or any other) please open a new issue to ask it.  Otherwise, what is it you need help with?

**Comment by AniesAliasGethub1** [comment]
Ok thank you so much

في الأربعاء، ٩ سبتمبر، ٢٠٢٠ ١١:٢٣ ص Evan Nemerson <notifications@github.com>
كتب:

**Pull request closed without merging**
