### PR TITLE
Fixed simde_mm_prefetch warnings

### PR DESCRIPTION
**Pull request by Epixu**
Closes: #996

### CODE REVIEW

**Comment by Epixu** [comment]
#996

**Comment by mr-c** [comment]
@epixu Any thoughts on this emscripten error?

https://github.com/simd-everywhere/simde/actions/runs/4411656252/jobs/7731674536?pr=997#step:8:606

>  unexpected runtime library name: roundevenf

**Comment by Epixu** [comment]
> @Epixu Any thoughts on this emscripten error?
> 
> https://github.com/simd-everywhere/simde/actions/runs/4411656252/jobs/7731674536?pr=997#step:8:606
> 
> > unexpected runtime library name: roundevenf

Sorry, I have no idea what it is about, it shouldn't be related to my warnings fix afaik.

**Review by mr-c — APPROVED** [review]

**Comment by mr-c** [comment]
Fixed in https://github.com/simd-everywhere/simde/commit/9c3d0dc0b20c019b8ef19ebf8e44cd3fe6fb1aa2

**Pull request closed without merging**
