### PR TITLE
Fix and improve abs functions on SSE

### PR DESCRIPTION
**Pull request by jpcima**
As described in #704

### CODE REVIEW

**Comment by jpcima** [comment]
Reverted jpcima/simde@9817f8c
because it implemented SSE with some SSE2-only intrinsics
Given that it's platform-dependent code, the union method is not really that inconvenient, or is it?

**Comment by nemequ** [comment]
> Reverted [jpcima/simde@9817f8c](https://github.com/jpcima/simde/commit/9817f8c)
> because it implemented SSE with some SSE2-only intrinsics
> Given that it's platform-dependent code, the union method is not really that inconvenient, or is it?

Nope, but you could do it using SSE intrinsics: `return _mm_and_ps(_mm_set1_ps(SIMDE_MATH_NANF), a)`.  TBH I'm not sure it's worth it, though; SSE2's market penetration on x86 is basically 100% (on the [Steam Hardware Survey](https://store.steampowered.com/hwsurvey) it actually rounds to 100%).

Just out of curiousity, were you having a problem with the AVX-512 implementation?  FP exceptions from garbage in the upper 384-bits, maybe?  I was thinking about suggesting we just use `_mm512_mask_abs_ps` with all zeros for the src parameter, but I just saw that instruction has a latency of 8 and now I'm not sure why it even exists… I'm honestly considering implementing `simde_mm512_abs_ps` using `_mm512_and_ps` in SIMDe.

**Comment by jpcima** [comment]
I'll just skip on the SSE1 versions of the pd variant, but I'm adding a test case that triggers the bug about mantissa bits overwritten with 0.
The reason that I remove AVX, like you observed, it's because of latency 8.
Despite of throughput 0.5, I have intuition that SSE will be more useful in a vast majority of cases.

**Comment by jpcima** [comment]
It's done, good for review.
Regarding the test, it's as said in comment: https://github.com/simd-everywhere/simde/issues/704#issuecomment-780246507
Ideally it's written as exact comparison, but I don't know how to edit simde for this, so I leave it to you.

**Comment by jpcima** [comment]
Update: rebase on master, add unit tests which are able to trigger the mantissa corruption issue
Also added unit test helpers for exact float comparison.
Are these appropriate?

**Comment by nemequ** [comment]
Sorry, I've been without internet access for a while :(

Thanks for tracking this down, and *especially* for finding a way to test this.  Most people would have just tried to get the code working and moved on, I'm really glad you didn't do that :)

Normally an exact test isn't a good idea because we would need a ton of digits for each floating point value in the test vectors, but for abs I think it should be safe since the error should be the same for both.  The implementation seems a bit heavy-handed, though.  Maybe instead of duplicating all the test macros/functions we could just allow people to pass `INT_MAX` for the precision and add special cases to `simde_test_f{32,64}_precision_to_slop` to just `return (slop == INT_MAX) ? SIMDE_FLOAT32_C(0.0) : (...);`, and maybe a special case for 0.0 in `simde_test_equal_f{32,64}`?

**Comment by jpcima** [comment]
> we could just allow people to pass INT_MAX for the precision

The expansion `1e-##precision` expects a literal but `INT_MAX` can't necessarily be expected to be one.
Also some compilers will throw a warning if a too small float literal equals zero.

**Comment by nemequ** [comment]
Hm, I thought I had removed all usage of `1e-##precision` in favor of the *_to_slop functions (in 45fa2c74f55bcbd7c5456da1a1112b822376d99d), but it looks like I missed the ones outside of test.h.  Those should be replaced.

I'm going to be *very* busy today, but I'll try to swap out the `1e-##precision` stuff and get this merged tomorrow.  Thanks again for all the work you've done on this, and sorry it took so long for me to review it.

**Comment by nemequ** [comment]
Merged, thanks again, and sorry about the delay :(

**Pull request closed without merging**
