### PR TITLE
AVX512F/fmaddsub: Implement Instruction

### PR DESCRIPTION
**Pull request by robinchrist**
First implementation of AVX512 fmaddsub (`_mm512_fmaddsub_pd` and `_mm512_fmaddsub_ps`), see https://github.com/simd-everywhere/simde/issues/1243

Current status:
No tests yet. This is just to see whether the header itself could be merged style-wise.

### CODE REVIEW

**Comment by mr-c** [comment]
This looks like the correct direction, yes!

Please review the linter / formating results at https://github.com/simd-everywhere/simde/actions/runs/12282344329/job/34273355555?pr=1246

You'll also need an entry for `avx512/fmaddsub.h` in https://github.com/simd-everywhere/simde/blob/fa6a8690b84e242c6be426522c8ce282ca33fa2b/simde/x86/avx512.h#L70-L74

See also https://github.com/simd-everywhere/simde/wiki/Implementing-a-New-Function for hints about generating the tests. I can also help you with that.

**Comment by robinchrist** [comment]
I'll try to add the tests later today

**Comment by robinchrist** [comment]
This pipeline is massive... But looking good so far. Anything else I need to adjust?

**Comment by mr-c** [comment]
@robinchrist the CI is looking good! Did you generate the test arrays on a machine that supports AVX512F? If not, let me know and I'll run them on real hardware. The CI uses an emulator from Intel, but I like to double check with real silicon.

**Comment by robinchrist** [comment]
@mr-c All my AVX512 machines are currently not available, so if possible it would be good if you tested on a CPU with native AVX512. If not possible, I‘ll try to get one of my Cascade Lake machines up and running this weekend

**Comment by mr-c** [comment]
@robinchrist I ran the tests on a `AMD EPYC 9454` using gcc 12.2.0-14 (from Debian) and your tests pass!

**Comment by robinchrist** [comment]
@mr-c Amazing! So I guess we're ready to merge now?

**Review by mr-c — APPROVED** [review]

**Comment by mr-c** [comment]
@robinchrist Nearly there! I'll merge after a few more CIs pass

**Pull request merged**
