### PR TITLE
avx512/load_ps: implementation

### LINKED ISSUE #930: Is `simde_mm512_load_ps` missing?
Hi,

thank you very much for this cool library.

I noticed that `simde_mm512_load_ps` is missing while `simde_mm512_loadu_ps` is implemented. However, both seem to exist for Intel intrinsics (see screenshot). Maybe I oversaw one or maybe they do the same anyways?

Thanks
Lukas

Screenshot from 2021-10-25 13-28-29

### PR DESCRIPTION
**Pull request by operasfantom**
Implementation of `simde_mm512_load_ps` is based on implementation of `simde_mm512_load_si512`. Test data of `test_simde_mm512_load_ps` is copied from `test_simde_mm512_store_ps` and adjusted as done in `test_simde_mm256_load_ps`.

closes #930

### CODE REVIEW

**Comment by operasfantom** [comment]
Hello @nemequ and @mr-c,

I am not quite sure how contributing to SIMDe goes at present. However, I would like to dedicate myself to that and start with this little contribution. Can you review in your spare time and correct me in case I am doing something wrong, please? Thanks in advance!

Regards,
Pavel

**Comment by operasfantom** [comment]
Not entirely sure if these failing jobs are due to my change. Can someone look at these?

**Comment by mr-c** [comment]
Hello @operasfantom ; sorry for the late reply. We've finally fixed our CI issues, so I am rebasing your PRs to test them.

**Comment by operasfantom** [comment]
> Hello @operasfantom ; sorry for the late reply. We've finally fixed our CI issues, so I am rebasing your PRs to test them.

Hey @mr-c , thank you for having it fixed eventually. Let me know if you have any questions or some action is required for me, once we achieve green CI.

**Comment by mr-c** [comment]
Thank you @operasfantom ; this was merged as https://github.com/simd-everywhere/simde/commit/d5880491cc07564a01f840b580d59701a51bb082

**Pull request closed without merging**
