### PR TITLE
NEON: implement aes intrinsics

### PR DESCRIPTION
**Pull request by yyctw**
Hi all, this is Eric from Andes Technology Corporation. This PR includes 4 initial implementations of AES intrinsics.

### CODE REVIEW

**Comment by yyctw** [comment]
Based on the previous comments (https://github.com/simd-everywhere/simde/pull/1093#pullrequestreview-1701300915), it appears that three functions (`simde_x_aes_shift_rows `, `simde_x_aes_inv_shift_rows`, and `simde_x_aes_coef_mult_lookup`) are redundantly implemented in both Neon and x86.

However, I found that the arrangement and shifting result of the matrix are not the same. For example, in the case of `simde_x_aes_shift_rows()`, NEON's implementation transforms the matrix from A to B, whereas x86's implementations transform the matrix from C to D. I thought that they could not be reused.

```
simde_x_aes_shift_rows()

          A                                         B
|  15  14  13  12  |                      |  11    6   1  12  |
|  11  10   9   8  |        NEON          |   7    2  13   8  |
|   7   6   5   4  |    ------------>     |   3   14   9   4  |
|   3   2   1   0  |                      |  15   10   5   0  |

          C                                          D
|   0   1   2   3  |                       |   0   1   2   3  |
|   4   5   6   7  |          x86          |   5   6   7   4  |
|   8   9  10  11  |    ------------>      |  10  11   8   9  |
|  12  13  14  15  |                       |  15  12  13  14  |
```

**Comment by mr-c** [comment]
@lin72h , any thoughts?

**Comment by lin72h** [comment]
> @lin72h , any thoughts?

I just amazed by the progress you guys made, I'm not very family with the AES instructions between the 2 architecture. Sorry can't give any suggestion

**Comment by mr-c** [comment]
Thank you @yyctw !

**Pull request merged**
