### PR TITLE
sse2 mm_pause: more archs, add a basic test

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by mr-c** [comment]
@junaruga Do you know why the rpm-builds did not start?

**Comment by junaruga** [comment]
@mr-c I found Packit's status page. It seems the Copr used to build is outage right now.

https://status.packit.dev/
> [Copr frontend instability →](https://status.packit.dev/issues/2023-09-05-copr-outage/)
> Copr is experiencing issues with its [frontend](https://github.com/fedora-copr/copr/issues/2897) which is currently mitigated while Copr team investigates.
>
> In case some of your builds were not submitted, please retrigger.

In other words, I can see that there are other applications running Copr.
https://dashboard.packit.dev/pipelines

So, I think the workaround is to try this PR such as by adding empty commit, the rebase the PR by squashing.

```
$ git commit --allow-empty
$ git rebase -i <a commit>
```

**Comment by mr-c** [comment]
Thanks for checking @junaruga ; `git commit --amend  --reset-author` seems to have worked

**Comment by junaruga** [comment]
Good to know it!

**Pull request merged**
